name: robbiebeta
favicon: null
layout_spectrum: 0.28851
typography_spectrum: 0.14653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5865757912397385
  lightness: 0.510658472776413
  saturation: 0.2825989432167262
  rhythmicContrast: 0.9601353949401528
purpose: []
