name: robbiebeta
favicon: null
layout_spectrum: 0.28851
typography_spectrum: 0.14653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#000000'
    - '#018dc8'
    - '#949494'
    - '#5b5b5b'
  brandStrength: 0.5865757912397385
  lightness: 0.1875
  saturation: 0.6875
  rhythmicContrast: 0.9601353949401528
purpose: []
